# Generated by Django 5.0.2 on 2024-03-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='firebase_id',
        ),
        migrations.AddField(
            model_name='users',
            name='referal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
