# Generated by Django 5.0.2 on 2024-03-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_users_firebase_id_users_referal_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
