# Generated by Django 5.0.2 on 2024-03-06 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='roles',
        ),
        migrations.AddField(
            model_name='users',
            name='user_role',
            field=models.ForeignKey(db_column='user_role_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.role'),
        ),
    ]
