# Generated by Django 5.0.2 on 2024-03-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_users_roles_users_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_role',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(db_column='role_id', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='app.role'),
        ),
    ]
