# Generated by Django 5.0.2 on 2024-03-24 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countery_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country_logo', models.ImageField(blank=True, null=True, upload_to='country_images/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='country_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_country', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'country_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VisaTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_logo', models.ImageField(blank=True, null=True, upload_to='country_images/')),
                ('Visa_Types', models.CharField(blank=True, choices=[('visit visa', 'visit visa'), ('Tourist Visa', 'Tourist Visa'), ('Study Visa', 'Study Visa'), ('Medical Visa', 'Medical Visa'), ('Migration Visa', 'Migration Visa'), ('Family Visa', 'Family Visa'), ('Diplomatic Visa', 'Diplomatic Visa'), ('Working Visa', 'Working Visa'), ('Business Visa', 'Business Visa')], default='visit visa', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Country', models.ForeignKey(db_column='Country_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.country')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_country_type', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visa_types_list',
                'managed': True,
            },
        ),
    ]
