# Generated by Django 5.0.2 on 2024-03-24 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_country_visatypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visatypes',
            name='Country',
            field=models.ForeignKey(db_column='Country_countery_name', on_delete=django.db.models.deletion.DO_NOTHING, to='app.country'),
        ),
    ]
