# Generated by Django 4.1.2 on 2024-05-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_country_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('staff', 'staff'), ('customer', 'customer')], default='admin', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
