# Generated by Django 4.1.2 on 2024-05-01 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_users_role_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationNo', models.IntegerField()),
                ('phone_number_two', models.CharField(blank=True, max_length=13, null=True)),
                ('upload_passport_front', models.ImageField(blank=True, null=True, upload_to='visaapplication/')),
                ('upload_passport_back', models.ImageField(blank=True, null=True, upload_to='visaapplication/')),
                ('aadhar_front', models.ImageField(blank=True, null=True, upload_to='visaapplication/')),
                ('aadhar_back', models.ImageField(blank=True, null=True, upload_to='visaapplication/')),
                ('user', models.ForeignKey(db_column='user_visa_application_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visa_application',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('questio1', models.CharField(max_length=255)),
                ('answer1', models.CharField(max_length=255)),
                ('questio2', models.CharField(max_length=255)),
                ('answer2', models.CharField(max_length=255)),
                ('questio3', models.CharField(max_length=255)),
                ('answer3', models.CharField(max_length=255)),
                ('application_user', models.ForeignKey(db_column='visaApplication_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.visaapplication')),
            ],
            options={
                'db_table': 'security_question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PointOfContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('application_user', models.ForeignKey(db_column='visaApplication_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.visaapplication')),
            ],
            options={
                'db_table': 'point_of_contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DependentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dependent_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dependent_email', models.EmailField(max_length=254)),
                ('dependent_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('dependent_phone_number_two', models.CharField(blank=True, max_length=13, null=True)),
                ('upload_passport_front', models.ImageField(blank=True, null=True, upload_to='visaapplication/')),
                ('upload_passport_back', models.ImageField(blank=True, null=True, upload_to='visaapplication/')),
                ('aadhar_front', models.ImageField(blank=True, null=True, upload_to='visaapplication/')),
                ('aadhar_back', models.ImageField(blank=True, null=True, upload_to='visaapplication/')),
                ('application_user', models.ForeignKey(db_column='VisaApplication_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.visaapplication')),
            ],
            options={
                'db_table': 'dependent_list',
                'managed': True,
            },
        ),
    ]
