# Generated by Django 4.1.2 on 2024-06-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_visaapplication_securityquestion_pointofcontact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointofcontact',
            old_name='address_line1',
            new_name='relation_ship',
        ),
        migrations.RenameField(
            model_name='pointofcontact',
            old_name='address_line2',
            new_name='street_name',
        ),
        migrations.AddField(
            model_name='pointofcontact',
            name='street_name_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
