# Generated by Django 4.1.2 on 2024-06-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_address_line1_pointofcontact_relation_ship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofcontact',
            name='organization_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pointofcontact',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
