# Generated by Django 4.1.2 on 2024-06-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_pointofcontact_organization_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofcontact',
            name='professional_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
