# Generated by Django 4.1.2 on 2024-07-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_ceac_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='country',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='visa_type',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
    ]
