# Generated by Django 4.1.2 on 2024-07-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_visaapplication_country_visaapplication_visa_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='visatypes',
            name='Visa_Types',
            field=models.CharField(blank=True, choices=[('visit', 'visit'), ('Tourist', 'Tourist'), ('Study', 'Study'), ('Medical', 'Medical'), ('Migration', 'Migration'), ('Family', 'Family'), ('Diplomatic', 'Diplomatic'), ('Working', 'Working'), ('Business', 'Business')], default='visit visa', max_length=100, null=True),
        ),
    ]
