# Generated by Django 4.1.2 on 2024-08-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_users_videos_show_alter_contact_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
