# Generated by Django 4.1.2 on 2024-08-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_visaapplication_aadhar_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='doc_1',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='doc_2',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
