# Generated by Django 5.0.7 on 2024-11-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_users_videos_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city_or_state', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='reviews/')),
                ('review_message', models.TextField()),
                ('is_approved', models.CharField(blank=True, choices=[('approved', 'approved'), ('notapproved', 'notapproved')], default='notapproved', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Reviews',
                'managed': True,
            },
        ),
    ]
